### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Hasegawa1121** [Hasegawa1121/furima-28791#10]
## URL
https://furima-28791.herokuapp.com/

## BASIC認証
ID : admin
password : 2222

## 出品者アカウント
Email : sample@sample.com
Password : abcd1234

## 購入者アカウント
Email : test@test.com
Password : abcd1234

## テスト用クレジットカード
番号 : 4242424242424242
期限 : 2 / 22
cvc : 222

**Comment by oshim0115** [comment]
長谷川さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
